version: '3.9'

services:
  db:
    container_name: anki-database
    build:
      dockerfile: Database/Dockerfile
      context: .
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/postgresql/data
      - type: bind
        source: ./Database/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./config/postgresql.config
        target: /etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  db-store: